<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?=options('class_name')?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?=css('main.css')?>">
    <?php if ($user_style): ?>
      <link
        rel="stylesheet"
        as="style"
        blocking="render"
        href="<?=$user_style?>"
      >
    <?php endif; ?>
</head>
<body class="<?=$this->template()?>-template <?= join(' ' , $body_class); ?>">
  <nav>
    <h1><a href="<?=link_url('')?>"><?=options('class_name')?></a></h1>
    <h2><a href="<?=link_url('')?>"><?=options('term')?></a></h2>
    <ul>
      <li><a href="<?=link_url('')?>">Syllabus</a></li>
      <?php if (options('has_schedule')): ?>
        <li><a href="<?=link_url('schedule')?>">Schedule</a></li>
      <?php endif; ?>
      <?php if (options('has_projects')): ?>
        <li><a href="<?=link_url('projects')?>">Projects</a></li>
      <?php endif; ?>
      <?php if ($pages): ?>
        <?php foreach($pages as $page): if ($page['show_in_nav'] == true): ?>
          <li><a href="<?=link_url($page['slug'])?>"><?=$page['name']?></a></li>
        <?php endif; endforeach; ?>
      <?php endif; ?>
    </ul>
  </nav>
  <main>
    <?= $yield; ?>
  </main>
</body>
</html>
