<ol class="schedule">
<?php foreach($schedule as $week_num=>$week):
	if ($week_num == 'holiday') {
		continue;
	}
?>
	<li class="week">
		<h1 class="week-number">Week <?=$week_num?></h1>
		<ol class="week-content">
			<?php foreach($week as $day_num=>$day): ?>
				<li class="week-day">
					<h2 class="week-day-date <?= isset($schedule['holiday']["$week_num.$day_num"]) ? 'holiday' : '' ?>">
						<?=date_for_week_and_day($week_num, $day_num)->format('l n/j');?>
					</h2>
					<div class="week-day-content">
						<?= $schedule[$week_num][$day_num]; ?>
					</div>
				</li>
			<?php endforeach; ?>
		</ol>
	</li>
<?php endforeach; ?>
</ol>